// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Andorra */
export const AD: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 24,
  bbanRegExp: /^[0-9]{8}[A-Z0-9]{12}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  branchPosition: [4, 7],
  accountPosition: [12, 23],
});
