// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Albania */
export const AL: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[0-9]{8}[A-Z0-9]{16}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 2],
  branchPosition: [3, 7],
  accountPosition: [12, 28],
});
