// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Åland Islands */
export const AX: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 18,
  bbanRegExp: /^[0-9]{14}$/u,
  ibanRegistry: true,
  sepa: true,
});
