// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkMod9710BBAN } from '../validators/mod97-10';

/** Bosnia and Herzegovina */
export const BA: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 20,
  bbanRegExp: /^[0-9]{16}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 2],
  branchPosition: [3, 5],
  bbanValidator: checkMod9710BBAN,
});
