// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkBelgianBBAN } from '../validators/be';

/** Belgium */
export const BE: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 16,
  bbanRegExp: /^[0-9]{12}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
  accountPosition: [7, 13],
  bbanValidator: checkBelgianBBAN,
});
