// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Burundi */
export const BI: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 27,
  bbanRegExp: /^[0-9]{23}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 4],
  branchPosition: [5, 9],
  accountPosition: [14, 27],
});
