// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Brazil */
export const BR: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 29,
  bbanRegExp: /^[A-Z0-9]{8}[0-9]{15}[A-Z0-9]{2}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 7],
  branchPosition: [8, 12],
  accountPosition: [17, 29],
});
