// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Congo */
export const CG: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 27,
  bbanRegExp: /^[0-9]{23}$/u,
  ibanRegistry: false,
  sepa: false,
});
