// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Côte d'Ivoire */
export const CI: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[A-Z]{1}[0-9]{23}$/u,
  ibanRegistry: false,
  sepa: false,
});
