// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Germany */
export const DE: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 22,
  bbanRegExp: /^[0-9]{18}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 7],
  accountPosition: [12, 21],
});
