// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkEstonianBBAN } from '../validators/ee';

/** Estonia */
export const EE: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 20,
  bbanRegExp: /^[0-9]{16}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 1],
  accountPosition: [6, 19],
  bbanValidator: checkEstonianBBAN,
});
