// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Egypt */
export const EG: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 29,
  bbanRegExp: /^[0-9]{25}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  branchPosition: [4, 7],
  accountPosition: [12, 28],
});
