// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkSpainBBAN } from '../validators/es';

/** Spain */
export const ES: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 24,
  bbanRegExp: /^[0-9]{20}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  branchPosition: [4, 7],
  accountPosition: [14, 24],
  bbanValidator: checkSpainBBAN,
});
