// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Falkland Islands (Malvinas) */
export const FK: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 18,
  bbanRegExp: /^[A-Z]{2}[0-9]{12}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 1],
  accountPosition: [6, 18],
});
