// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkFrenchBBAN } from '../validators/fr';

/** France */
export const FR: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 27,
  bbanRegExp: /^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 4],
  branchPosition: [5, 9],
  accountPosition: [14, 24],
  bbanValidator: checkFrenchBBAN,
});
