// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** United Kingdom */
export const GB: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 22,
  bbanRegExp: /^[A-Z]{4}[0-9]{14}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  branchPosition: [4, 9],
});
