// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Gibraltar */
export const GI: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 23,
  bbanRegExp: /^[A-Z]{4}[A-Z0-9]{15}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  accountPosition: [8, 23],
});
