// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Greenland */
export const GL: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 18,
  bbanRegExp: /^[0-9]{14}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 17],
});
