// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Greece */
export const GR: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 27,
  bbanRegExp: /^[0-9]{7}[A-Z0-9]{16}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
  branchPosition: [3, 6],
  accountPosition: [11, 26],
});
