// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Guinea-Bissau */
export const GW: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 25,
  bbanRegExp: /^[A-Z]{2}[0-9]{19}$/u,
  ibanRegistry: false,
  sepa: false,
});
