// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Honduras */
export const HN: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[A-Z]{4}[0-9]{20}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 28],
});
