// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkCroatianBBAN } from '../validators/hr';

/** Croatia */
export const HR: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 21,
  bbanRegExp: /^[0-9]{17}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 6],
  bbanValidator: checkCroatianBBAN,
});
