// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkHungarianBBAN } from '../validators/hu';

/** Hungary */
export const HU: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[0-9]{24}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
  branchPosition: [3, 6],
  bbanValidator: checkHungarianBBAN,
});
