// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Israel */
export const IL: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 23,
  bbanRegExp: /^[0-9]{19}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 2],
  branchPosition: [3, 5],
});
