// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Iraq */
export const IQ: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 23,
  bbanRegExp: /^[A-Z]{4}[0-9]{15}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  branchPosition: [4, 6],
  accountPosition: [11, 23],
});
