// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Iran */
export const IR: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 26,
  bbanRegExp: /^[0-9]{22}$/u,
  ibanRegistry: false,
  sepa: false,
});
