// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Iceland */
export const IS: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 26,
  bbanRegExp: /^[0-9]{22}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 1],
  branchPosition: [2, 3],
  accountPosition: [8, 25],
});
