// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Italy */
export const IT: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 27,
  bbanRegExp: /^[A-Z]{1}[0-9]{10}[A-Z0-9]{12}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [1, 5],
  branchPosition: [6, 10],
  accountPosition: [15, 26],
});
