// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Kuwait */
export const KW: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 30,
  bbanRegExp: /^[A-Z]{4}[A-Z0-9]{22}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 29],
});
