// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Kazakhstan */
export const KZ: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 20,
  bbanRegExp: /^[0-9]{3}[A-Z0-9]{13}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 2],
  accountPosition: [7, 19],
});
