// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Lebanon */
export const LB: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[0-9]{4}[A-Z0-9]{20}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [14, 28],
});
