// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Saint Lucia */
export const LC: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 32,
  bbanRegExp: /^[A-Z]{4}[A-Z0-9]{24}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 32],
});
