// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Liechtenstein */
export const LI: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 21,
  bbanRegExp: /^[0-9]{5}[A-Z0-9]{12}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 4],
});
