// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Latvia */
export const LV: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 21,
  bbanRegExp: /^[A-Z]{4}[A-Z0-9]{13}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  accountPosition: [8, 20],
});
