// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Libya */
export const LY: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 25,
  bbanRegExp: /^[0-9]{21}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 2],
  branchPosition: [3, 5],
  accountPosition: [10, 25],
});
