// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Morocco */
export const MA: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[0-9]{24}$/u,
  ibanRegistry: false,
  sepa: false,
});
