// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Moldova, Republic of */
export const MD: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 24,
  bbanRegExp: /^[A-Z0-9]{20}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 1],
  accountPosition: [6, 24],
});
