// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkMod9710BBAN } from '../validators/mod97-10';

/** North Macedonia */
export const MK: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 19,
  bbanRegExp: /^[0-9]{3}[A-Z0-9]{10}[0-9]{2}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
  bbanValidator: checkMod9710BBAN,
});
