// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Mongolia */
export const MN: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 20,
  bbanRegExp: /^[0-9]{16}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 20],
});
