// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Martinique */
export const MQ: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 27,
  bbanRegExp: /^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$/u,
  ibanRegistry: true,
  sepa: true,
});
