// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Malta */
export const MT: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 31,
  bbanRegExp: /^[A-Z]{4}[0-9]{5}[A-Z0-9]{18}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  branchPosition: [4, 8],
  accountPosition: [13, 30],
});
