// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Mauritius */
export const MU: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 30,
  bbanRegExp: /^[A-Z]{4}[0-9]{19}[A-Z]{3}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 5],
  branchPosition: [6, 7],
  accountPosition: [12, 23],
});
