// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Mozambique */
export const MZ: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 25,
  bbanRegExp: /^[0-9]{21}$/u,
  ibanRegistry: false,
  sepa: false,
});
