// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Netherlands (The) */
export const NL: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 18,
  bbanRegExp: /^[A-Z]{4}[0-9]{10}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  accountPosition: [8, 18],
});
