// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkNorwayBBAN } from '../validators/no';

/** Norway */
export const NO: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 15,
  bbanRegExp: /^[0-9]{11}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  accountPosition: [8, 14],
  bbanValidator: checkNorwayBBAN,
});
