// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkPolandBBAN } from '../validators/pl';

/** Poland */
export const PL: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[0-9]{24}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 7],
  accountPosition: [12, 27],
  bbanValidator: checkPolandBBAN,
});
