// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Palestine, State of */
export const PS: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 29,
  bbanRegExp: /^[A-Z]{4}[A-Z0-9]{21}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 28],
});
