// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkMod9710BBAN } from '../validators/mod97-10';

/** Portugal */
export const PT: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 25,
  bbanRegExp: /^[0-9]{21}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 3],
  bbanValidator: checkMod9710BBAN,
});
