// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkMod9710BBAN } from '../validators/mod97-10';

/** Serbia */
export const RS: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 22,
  bbanRegExp: /^[0-9]{18}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
  bbanValidator: checkMod9710BBAN,
});
