// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Russian Federation */
export const RU: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 33,
  bbanRegExp: /^[0-9]{14}[A-Z0-9]{15}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 8],
  branchPosition: [9, 13],
  accountPosition: [13, 33],
});
