// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Saudi Arabia */
export const SA: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 24,
  bbanRegExp: /^[0-9]{2}[A-Z0-9]{18}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 1],
  accountPosition: [6, 23],
});
