// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Sweden */
export const SE: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 24,
  bbanRegExp: /^[0-9]{20}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
});
