// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';
import { checkMod9710BBAN } from '../validators/mod97-10';

/** Slovenia */
export const SI: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 19,
  bbanRegExp: /^[0-9]{15}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 1],
  branchPosition: [2, 4],
  accountPosition: [9, 16],
  bbanValidator: checkMod9710BBAN,
});
