// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import type * as Types from '../core/types';
import { AD } from './AD';
import { AE } from './AE';
import { AL } from './AL';
import { AO } from './AO';
import { AT } from './AT';
import { AX } from './AX';
import { AZ } from './AZ';
import { BA } from './BA';
import { BE } from './BE';
import { BF } from './BF';
import { BG } from './BG';
import { BH } from './BH';
import { BI } from './BI';
import { BJ } from './BJ';
import { BL } from './BL';
import { BR } from './BR';
import { BY } from './BY';
import { CF } from './CF';
import { CG } from './CG';
import { CH } from './CH';
import { CI } from './CI';
import { CM } from './CM';
import { CR } from './CR';
import { CV } from './CV';
import { CY } from './CY';
import { CZ } from './CZ';
import { DE } from './DE';
import { DJ } from './DJ';
import { DK } from './DK';
import { DO } from './DO';
import { DZ } from './DZ';
import { EE } from './EE';
import { EG } from './EG';
import { ES } from './ES';
import { FI } from './FI';
import { FK } from './FK';
import { FO } from './FO';
import { FR } from './FR';
import { GA } from './GA';
import { GB } from './GB';
import { GE } from './GE';
import { GF } from './GF';
import { GI } from './GI';
import { GL } from './GL';
import { GP } from './GP';
import { GQ } from './GQ';
import { GR } from './GR';
import { GT } from './GT';
import { GW } from './GW';
import { HN } from './HN';
import { HR } from './HR';
import { HU } from './HU';
import { IE } from './IE';
import { IL } from './IL';
import { IQ } from './IQ';
import { IR } from './IR';
import { IS } from './IS';
import { IT } from './IT';
import { JO } from './JO';
import { KM } from './KM';
import { KW } from './KW';
import { KZ } from './KZ';
import { LB } from './LB';
import { LC } from './LC';
import { LI } from './LI';
import { LT } from './LT';
import { LU } from './LU';
import { LV } from './LV';
import { LY } from './LY';
import { MA } from './MA';
import { MC } from './MC';
import { MD } from './MD';
import { ME } from './ME';
import { MF } from './MF';
import { MG } from './MG';
import { MK } from './MK';
import { ML } from './ML';
import { MN } from './MN';
import { MQ } from './MQ';
import { MR } from './MR';
import { MT } from './MT';
import { MU } from './MU';
import { MZ } from './MZ';
import { NC } from './NC';
import { NE } from './NE';
import { NI } from './NI';
import { NL } from './NL';
import { NO } from './NO';
import { OM } from './OM';
import { PF } from './PF';
import { PK } from './PK';
import { PL } from './PL';
import { PM } from './PM';
import { PS } from './PS';
import { PT } from './PT';
import { QA } from './QA';
import { RE } from './RE';
import { RO } from './RO';
import { RS } from './RS';
import { RU } from './RU';
import { SA } from './SA';
import { SC } from './SC';
import { SD } from './SD';
import { SE } from './SE';
import { SI } from './SI';
import { SK } from './SK';
import { SM } from './SM';
import { SN } from './SN';
import { SO } from './SO';
import { ST } from './ST';
import { SV } from './SV';
import { TD } from './TD';
import { TF } from './TF';
import { TG } from './TG';
import { TL } from './TL';
import { TN } from './TN';
import { TR } from './TR';
import { UA } from './UA';
import { VA } from './VA';
import { VG } from './VG';
import { WF } from './WF';
import { XK } from './XK';
import { YE } from './YE';
import { YT } from './YT';

export {
  AD,
  AE,
  AL,
  AO,
  AT,
  AX,
  AZ,
  BA,
  BE,
  BF,
  BG,
  BH,
  BI,
  BJ,
  BL,
  BR,
  BY,
  CF,
  CG,
  CH,
  CI,
  CM,
  CR,
  CV,
  CY,
  CZ,
  DE,
  DJ,
  DK,
  DO,
  DZ,
  EE,
  EG,
  ES,
  FI,
  FK,
  FO,
  FR,
  GA,
  GB,
  GE,
  GF,
  GI,
  GL,
  GP,
  GQ,
  GR,
  GT,
  GW,
  HN,
  HR,
  HU,
  IE,
  IL,
  IQ,
  IR,
  IS,
  IT,
  JO,
  KM,
  KW,
  KZ,
  LB,
  LC,
  LI,
  LT,
  LU,
  LV,
  LY,
  MA,
  MC,
  MD,
  ME,
  MF,
  MG,
  MK,
  ML,
  MN,
  MQ,
  MR,
  MT,
  MU,
  MZ,
  NC,
  NE,
  NI,
  NL,
  NO,
  OM,
  PF,
  PK,
  PL,
  PM,
  PS,
  PT,
  QA,
  RE,
  RO,
  RS,
  RU,
  SA,
  SC,
  SD,
  SE,
  SI,
  SK,
  SM,
  SN,
  SO,
  ST,
  SV,
  TD,
  TF,
  TG,
  TL,
  TN,
  TR,
  UA,
  VA,
  VG,
  WF,
  XK,
  YE,
  YT,
};

/**
 * IBAN format rules, national BBAN validation, identifier positions and SEPA membership
 * for every country that uses IBAN. Positions are 0-based and inclusive: bank and branch
 * within the BBAN, account within the IBAN.
 */
export const ibanSpecs: Readonly<Record<string, Types.IBANCountrySpec>> = Object.freeze({
  AD,
  AE,
  AL,
  AO,
  AT,
  AX,
  AZ,
  BA,
  BE,
  BF,
  BG,
  BH,
  BI,
  BJ,
  BL,
  BR,
  BY,
  CF,
  CG,
  CH,
  CI,
  CM,
  CR,
  CV,
  CY,
  CZ,
  DE,
  DJ,
  DK,
  DO,
  DZ,
  EE,
  EG,
  ES,
  FI,
  FK,
  FO,
  FR,
  GA,
  GB,
  GE,
  GF,
  GI,
  GL,
  GP,
  GQ,
  GR,
  GT,
  GW,
  HN,
  HR,
  HU,
  IE,
  IL,
  IQ,
  IR,
  IS,
  IT,
  JO,
  KM,
  KW,
  KZ,
  LB,
  LC,
  LI,
  LT,
  LU,
  LV,
  LY,
  MA,
  MC,
  MD,
  ME,
  MF,
  MG,
  MK,
  ML,
  MN,
  MQ,
  MR,
  MT,
  MU,
  MZ,
  NC,
  NE,
  NI,
  NL,
  NO,
  OM,
  PF,
  PK,
  PL,
  PM,
  PS,
  PT,
  QA,
  RE,
  RO,
  RS,
  RU,
  SA,
  SC,
  SD,
  SE,
  SI,
  SK,
  SM,
  SN,
  SO,
  ST,
  SV,
  TD,
  TF,
  TG,
  TL,
  TN,
  TR,
  UA,
  VA,
  VG,
  WF,
  XK,
  YE,
  YT,
});
