import {
  checkBelgianBBAN,
  checkCroatianBBAN,
  checkCzechAndSlovakBBAN,
  checkEstonianBBAN,
  checkFrenchBBAN,
  checkHungarianBBAN,
  checkMod9710BBAN,
  checkNorwayBBAN,
  checkPolandBBAN,
  checkSpainBBAN,
} from '../bban-validators';
import { type CountryMap } from '../core/types';
import { registrySpecs } from './registry';

/**
 * Values the SWIFT IBAN Registry does not define, merged over the generated `registrySpecs`:
 * - national checksum validators (`bbanValidator`)
 * - account number positions (`accountPosition`, 0-based within the IBAN)
 * - countries and territories outside the registry, such as those covered by the FR and FI entries
 * - deliberate deviations: FR also has a branch identifier, and SI splits its bank code into bank and branch
 */
const overrides: CountryMap = {
  AD: { accountPosition: [12, 23] },
  AE: { accountPosition: [7, 23] },
  AL: { accountPosition: [12, 28] },
  AO: { ibanLength: 25, bbanPattern: '^[0-9]{21}$', ibanRegistry: false },
  AX: { ibanLength: 18, bbanPattern: '^[0-9]{14}$', ibanRegistry: true },
  AZ: { accountPosition: [8, 27] },
  BA: { bbanValidator: checkMod9710BBAN },
  BE: { bbanValidator: checkBelgianBBAN, accountPosition: [7, 13] },
  BF: { ibanLength: 28, bbanPattern: '^[A-Z0-9]{2}[0-9]{22}$', ibanRegistry: false },
  BH: { accountPosition: [8, 22] },
  BI: { accountPosition: [14, 27] },
  BJ: { ibanLength: 28, bbanPattern: '^[A-Z0-9]{2}[0-9]{22}$', ibanRegistry: false },
  BL: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: false },
  BR: { accountPosition: [17, 29] },
  CF: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  CG: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  CI: { ibanLength: 28, bbanPattern: '^[A-Z]{1}[0-9]{23}$', ibanRegistry: false },
  CM: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  CR: { accountPosition: [8, 22] },
  CV: { ibanLength: 25, bbanPattern: '^[0-9]{21}$', ibanRegistry: false },
  CY: { accountPosition: [12, 28] },
  CZ: { bbanValidator: checkCzechAndSlovakBBAN },
  DE: { accountPosition: [12, 21] },
  DJ: { accountPosition: [14, 27] },
  DK: { accountPosition: [8, 17] },
  DO: { accountPosition: [8, 28] },
  DZ: { ibanLength: 26, bbanPattern: '^[0-9]{22}$', ibanRegistry: false },
  EE: { bbanValidator: checkEstonianBBAN, accountPosition: [6, 19] },
  EG: { accountPosition: [12, 28] },
  ES: { bbanValidator: checkSpainBBAN, accountPosition: [14, 24] },
  FI: { accountPosition: [7, 17] },
  FK: { accountPosition: [6, 18] },
  FO: { accountPosition: [8, 17] },
  FR: { bbanValidator: checkFrenchBBAN, branchPosition: [5, 9], accountPosition: [14, 24] },
  GA: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  GE: { accountPosition: [6, 22] },
  GF: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  GI: { accountPosition: [8, 23] },
  GL: { accountPosition: [8, 17] },
  GP: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  GQ: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  GR: { accountPosition: [11, 26] },
  GT: { accountPosition: [8, 28] },
  GW: { ibanLength: 25, bbanPattern: '^[A-Z]{2}[0-9]{19}$', ibanRegistry: false },
  HN: { accountPosition: [8, 28] },
  HR: { bbanValidator: checkCroatianBBAN },
  HU: { bbanValidator: checkHungarianBBAN },
  IQ: { accountPosition: [11, 23] },
  IR: { ibanLength: 26, bbanPattern: '^[0-9]{22}$', ibanRegistry: false },
  IS: { accountPosition: [8, 25] },
  IT: { accountPosition: [15, 26] },
  KM: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  KW: { accountPosition: [8, 29] },
  KZ: { accountPosition: [7, 19] },
  LB: { accountPosition: [14, 28] },
  LC: { accountPosition: [8, 32] },
  LV: { accountPosition: [8, 20] },
  LY: { accountPosition: [10, 25] },
  MA: { ibanLength: 28, bbanPattern: '^[0-9]{24}$', ibanRegistry: false },
  MC: { bbanValidator: checkFrenchBBAN },
  MD: { accountPosition: [6, 24] },
  ME: { bbanValidator: checkMod9710BBAN, accountPosition: [7, 19] },
  MF: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  MG: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  MK: { bbanValidator: checkMod9710BBAN },
  ML: { ibanLength: 28, bbanPattern: '^[A-Z0-9]{2}[0-9]{22}$', ibanRegistry: false },
  MN: { accountPosition: [8, 20] },
  MQ: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  MR: { accountPosition: [14, 24] },
  MT: { accountPosition: [13, 30] },
  MU: { accountPosition: [12, 23] },
  MZ: { ibanLength: 25, bbanPattern: '^[0-9]{21}$', ibanRegistry: false },
  NC: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  NE: { ibanLength: 28, bbanPattern: '^[A-Z]{2}[0-9]{22}$', ibanRegistry: false },
  NI: { accountPosition: [8, 28] },
  NL: { accountPosition: [8, 18] },
  NO: { bbanValidator: checkNorwayBBAN, accountPosition: [8, 14] },
  PF: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  PL: { bbanValidator: checkPolandBBAN, accountPosition: [12, 27] },
  PM: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  PS: { accountPosition: [8, 28] },
  PT: { bbanValidator: checkMod9710BBAN },
  QA: { accountPosition: [8, 29] },
  RE: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  RO: { accountPosition: [8, 23] },
  RS: { bbanValidator: checkMod9710BBAN },
  RU: { accountPosition: [13, 33] },
  SA: { accountPosition: [6, 23] },
  SC: { accountPosition: [12, 27] },
  SD: { accountPosition: [6, 18] },
  SI: {
    bbanValidator: checkMod9710BBAN,
    bankPosition: [0, 1],
    branchPosition: [2, 4],
    accountPosition: [9, 16],
  },
  SK: { bbanValidator: checkCzechAndSlovakBBAN },
  SN: { ibanLength: 28, bbanPattern: '^[A-Z]{2}[0-9]{22}$', ibanRegistry: false },
  SO: { accountPosition: [11, 23] },
  SV: { accountPosition: [8, 28] },
  TD: { ibanLength: 27, bbanPattern: '^[0-9]{23}$', ibanRegistry: false },
  TF: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  TG: { ibanLength: 28, bbanPattern: '^[A-Z]{2}[0-9]{22}$', ibanRegistry: false },
  TL: { accountPosition: [7, 20] },
  TN: { accountPosition: [9, 21] },
  UA: { accountPosition: [10, 28] },
  VA: { accountPosition: [7, 22] },
  VG: { accountPosition: [8, 24] },
  WF: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
  XK: { accountPosition: [8, 17] },
  YE: { accountPosition: [12, 30] },
  YT: { ibanLength: 27, bbanPattern: '^[0-9]{10}[A-Z0-9]{11}[0-9]{2}$', ibanRegistry: true },
};

/**
 * IBAN format rules, BBAN validation, and SEPA membership for countries that use IBAN.
 */
export const ibanSpecs: CountryMap = Object.fromEntries(
  [...new Set([...Object.keys(registrySpecs), ...Object.keys(overrides)])]
    .sort()
    .map((code) => [code, { ...registrySpecs[code], ...overrides[code] }]),
);
