// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Sao Tome and Principe */
export const ST: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 25,
  bbanRegExp: /^[0-9]{21}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  branchPosition: [4, 7],
});
