// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Togo */
export const TG: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 28,
  bbanRegExp: /^[A-Z]{2}[0-9]{22}$/u,
  ibanRegistry: false,
  sepa: false,
});
