// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Turkiye */
export const TR: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 26,
  bbanRegExp: /^[0-9]{6}[A-Z0-9]{16}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 4],
});
