// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Ukraine */
export const UA: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 29,
  bbanRegExp: /^[0-9]{6}[A-Z0-9]{19}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 5],
  accountPosition: [10, 28],
});
