// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Holy See */
export const VA: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 22,
  bbanRegExp: /^[0-9]{18}$/u,
  ibanRegistry: true,
  sepa: true,
  bankPosition: [0, 2],
  accountPosition: [7, 22],
});
