// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Virgin Islands (British) */
export const VG: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 24,
  bbanRegExp: /^[A-Z]{4}[0-9]{16}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  accountPosition: [8, 24],
});
