// Generated by registry/builder.mjs from iban-registry-v103.txt and overrides.mjs. Do not edit; run `npm run registry` instead.

import { type IBANCountrySpec } from '../core/types';

/** Yemen */
export const YE: IBANCountrySpec = Object.freeze<IBANCountrySpec>({
  ibanLength: 30,
  bbanRegExp: /^[A-Z]{4}[0-9]{4}[A-Z0-9]{18}$/u,
  ibanRegistry: true,
  sepa: false,
  bankPosition: [0, 3],
  branchPosition: [4, 7],
  accountPosition: [12, 30],
});
